name: model_editors
description: Editors for complex models and lists inspired by simplicity of TextEditingController, without manual state management.
version: 0.1.2
homepage: https://github.com/alexeyinkin/flutter-model-editors

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  model_interfaces: ^0.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
