name: model_editors
description: Editors for complex models and lists inspired by simplicity of TextEditingController, without manual state management.
version: 0.4.3
repository: https://github.com/alexeyinkin/flutter-model-editors

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter: { sdk: flutter }
  model_interfaces: ^0.3.1

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^3.4.0
